apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: superpods.crds.example.com
spec:
  group: crds.example.com
  names:
    kind: SuperPod
    listKind: SuperPodList
    plural: superpods
    shortNames:
      - sp
    singular: superpod
  scope: Namespaced
  version: v1